// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH9VhNJGG3dgds5uMrsZ5nqCBZiBQPGuw',
    appId: '1:242020444786:web:9b45d4ecd528dc14b270eb',
    messagingSenderId: '242020444786',
    projectId: 'project-furevr',
    authDomain: 'project-furevr.firebaseapp.com',
    storageBucket: 'project-furevr.appspot.com',
    measurementId: 'G-WXBCBS1SS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeKWSIf5sc0mj0jDImsiFrENoriA6fZBM',
    appId: '1:242020444786:android:a20b2a53388ed3f6b270eb',
    messagingSenderId: '242020444786',
    projectId: 'project-furevr',
    storageBucket: 'project-furevr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1FsFlIGdBpzTKjzRq5nfDmJcG72Vgf5M',
    appId: '1:242020444786:ios:4f15d5c8e2afe330b270eb',
    messagingSenderId: '242020444786',
    projectId: 'project-furevr',
    storageBucket: 'project-furevr.appspot.com',
    iosBundleId: 'com.example.furever',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1FsFlIGdBpzTKjzRq5nfDmJcG72Vgf5M',
    appId: '1:242020444786:ios:e3b3858ba9721d21b270eb',
    messagingSenderId: '242020444786',
    projectId: 'project-furevr',
    storageBucket: 'project-furevr.appspot.com',
    iosBundleId: 'com.example.furever.RunnerTests',
  );
}
